"""
Open Brain MCP Server
=====================
FastMCP server with four tools:
  - capture_thought   : save a new thought with embedding + metadata
  - semantic_search   : find thoughts by meaning
  - list_recent       : return the N most recently captured thoughts
  - get_stats         : aggregate statistics about the thought database

Embeddings are generated by calling the `embed` Supabase Edge Function so
that query vectors are produced by the same gte-small model as stored vectors.
No OpenAI or Anthropic key is needed here.

Required environment variables:
  SUPABASE_URL   e.g. https://<project>.supabase.co
  SUPABASE_KEY   service-role key
"""

import os
from datetime import datetime, timezone, timedelta
from typing import Any

import httpx
from fastmcp import FastMCP

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

SUPABASE_URL: str = os.environ["SUPABASE_URL"].rstrip("/")
SUPABASE_KEY: str = os.environ["SUPABASE_KEY"]

mcp = FastMCP(
    name="Open Brain",
    instructions=(
        "Memory system for capturing and retrieving thoughts. "
        "Use `capture_thought` to save a new thought or idea, "
        "`semantic_search` to find relevant memories, "
        "`list_recent` to browse the latest entries, "
        "and `get_stats` for an overview of the knowledge base."
    ),
)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _supabase_headers() -> dict[str, str]:
    return {
        "apikey": SUPABASE_KEY,
        "Authorization": f"Bearer {SUPABASE_KEY}",
        "Content-Type": "application/json",
    }


async def _embed(text: str) -> list[float]:
    """Call the `embed` Edge Function to get a gte-small vector."""
    async with httpx.AsyncClient(timeout=30) as client:
        resp = await client.post(
            f"{SUPABASE_URL}/functions/v1/embed",
            headers=_supabase_headers(),
            json={"text": text},
        )
        resp.raise_for_status()
        return resp.json()["embedding"]


# ---------------------------------------------------------------------------
# Tools
# ---------------------------------------------------------------------------

@mcp.tool()
async def capture_thought(content: str) -> dict[str, Any]:
    """
    Save a new thought to Open Brain.

    Args:
        content: The thought, idea, note, or task to remember.

    Returns:
        The saved thought with its id, extracted metadata, and created_at.
    """
    async with httpx.AsyncClient(timeout=60) as client:
        resp = await client.post(
            f"{SUPABASE_URL}/functions/v1/capture-thought",
            headers=_supabase_headers(),
            json={"content": content},
        )
        resp.raise_for_status()
        return resp.json()


@mcp.tool()
async def semantic_search(
    query: str,
    match_count: int = 5,
    match_threshold: float = 0.7,
) -> list[dict[str, Any]]:
    """
    Find thoughts semantically similar to *query*.

    Args:
        query:           Natural-language search query.
        match_count:     Maximum number of results to return (default 5).
        match_threshold: Minimum cosine similarity 0–1 (default 0.7).

    Returns:
        List of thoughts ordered by descending similarity, each with
        id, content, metadata, created_at, and similarity score.
    """
    embedding = await _embed(query)

    async with httpx.AsyncClient(timeout=30) as client:
        resp = await client.post(
            f"{SUPABASE_URL}/rest/v1/rpc/match_thoughts",
            headers=_supabase_headers(),
            json={
                "query_embedding": embedding,
                "match_threshold": match_threshold,
                "match_count": match_count,
            },
        )
        resp.raise_for_status()
        return resp.json()


@mcp.tool()
async def list_recent(limit: int = 10) -> list[dict[str, Any]]:
    """
    Return the *limit* most recently captured thoughts.

    Args:
        limit: Number of thoughts to return (default 10, max 100).

    Returns:
        List of thoughts ordered by created_at descending.
    """
    limit = min(max(1, limit), 100)

    async with httpx.AsyncClient(timeout=30) as client:
        resp = await client.get(
            f"{SUPABASE_URL}/rest/v1/thoughts",
            headers=_supabase_headers(),
            params={
                "select": "id,content,metadata,created_at",
                "order": "created_at.desc",
                "limit": limit,
            },
        )
        resp.raise_for_status()
        return resp.json()


@mcp.tool()
async def get_stats() -> dict[str, Any]:
    """
    Return aggregate statistics about the thought database.

    Returns a dict with:
        total_thoughts        : total row count
        thoughts_last_7_days  : thoughts captured in the past 7 days
        thoughts_last_30_days : thoughts captured in the past 30 days
        types_breakdown       : count per metadata.type value
        top_topics            : the 10 most frequently occurring topics
    """
    async with httpx.AsyncClient(timeout=30) as client:
        # Total count via Prefer: count=exact
        count_resp = await client.get(
            f"{SUPABASE_URL}/rest/v1/thoughts",
            headers={**_supabase_headers(), "Prefer": "count=exact"},
            params={"select": "id"},
        )
        count_resp.raise_for_status()
        content_range = count_resp.headers.get("content-range", "/0")
        total = int(content_range.split("/")[-1])

        # Fetch recent thoughts for time-window and breakdown analysis
        recent_resp = await client.get(
            f"{SUPABASE_URL}/rest/v1/thoughts",
            headers=_supabase_headers(),
            params={
                "select": "created_at,metadata",
                "order": "created_at.desc",
                "limit": 1000,
            },
        )
        recent_resp.raise_for_status()
        thoughts = recent_resp.json()

    now = datetime.now(timezone.utc)
    cutoff_7 = now - timedelta(days=7)
    cutoff_30 = now - timedelta(days=30)

    last_7 = 0
    last_30 = 0
    type_counts: dict[str, int] = {}
    topic_counts: dict[str, int] = {}

    for t in thoughts:
        try:
            ts = datetime.fromisoformat(t["created_at"].replace("Z", "+00:00"))
        except (KeyError, ValueError):
            continue

        if ts >= cutoff_7:
            last_7 += 1
        if ts >= cutoff_30:
            last_30 += 1

        meta = t.get("metadata") or {}
        thought_type = meta.get("type", "unknown")
        type_counts[thought_type] = type_counts.get(thought_type, 0) + 1

        for topic in meta.get("topics") or []:
            topic_counts[topic] = topic_counts.get(topic, 0) + 1

    top_topics = sorted(topic_counts.items(), key=lambda x: x[1], reverse=True)[:10]

    return {
        "total_thoughts": total,
        "thoughts_last_7_days": last_7,
        "thoughts_last_30_days": last_30,
        "types_breakdown": type_counts,
        "top_topics": [{"topic": t, "count": c} for t, c in top_topics],
    }


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    mcp.run()
